---
extends: "default"
ignore: |
  setup_files/
  compose.yaml
rules:
  comments: "enable"
  empty-values: "enable"
  indentation:
    indent-sequences: "consistent"
  line-length: "disable"
  quoted-strings:
    quote-type: "double"
