---
x-nautobot: &nautobot
  environment:
    NAUTOBOT_TOWER_URI: "https://awx:8043/"
  networks:
    - "default"
    - "awx"
services:
  nautobot:
    <<: *nautobot
  worker:
    <<: *nautobot
networks:
  awx: {}
